version: '3.1'

services:
  api:
    build: .
    command: sh -c "/wait && npx nodemon src/backend/index.js"
    volumes:
      - ./src/backend:/usr/app/src/backend:cached
      - ./node_modules:/usr/app/node_modules:cached
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      API_PORT: 8080
      DB_PORT: 3306
      DB_HOST: db
      DB_DATABASE: comp4004
      DB_USERNAME: root
      DB_PASSWORD: comp4004
      WAIT_HOSTS: db:3306

  web:
    build: .
    command: npx parcel src/frontend/src/index.html -p 8080
    volumes:
      - ./src/frontend:/usr/app/src/frontend:cached
      - ./node_modules:/usr/app/node_modules:cached
    ports:
      - "8081:8080"
    depends_on:
      - api
    environment:
      API_URL: "http://localhost:8080"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      DB_HOST: db
      MYSQL_DATABASE: comp4004
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: comp4004
    volumes:
      - ./src/db_scheme/comp5014_db_generation.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
