-- MySQL Script generated by MySQL Workbench
-- Fri Oct 30 23:09:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema comp4004
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema comp4004
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comp4004` DEFAULT CHARACTER SET utf8 ;
USE `comp4004` ;

-- -----------------------------------------------------
-- Table `comp4004`.`academic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`academic` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`academic` (
  `registration_deadline` DATETIME NOT NULL,
  `drop_deadline` DATETIME NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`admin` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`admin` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `admin_name` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`admin_id`),
  CONSTRAINT `fk_admin_login`
    FOREIGN KEY (`admin_id`)
    REFERENCES `comp4004`.`login` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`course` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_name` VARCHAR(45) NOT NULL,
  `course_status` VARCHAR(45) NOT NULL,
  `course_assigned_prof_id` INT NULL,
  `course_capacity` INT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_course_prof_idx` (`course_assigned_prof_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_prof`
    FOREIGN KEY (`course_assigned_prof_id`)
    REFERENCES `comp4004`.`prof` (`prof_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`course_slots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`course_slots` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`course_slots` (
  `course_id` INT NOT NULL,
  `course_slots_day` INT NOT NULL,
  `course_slots_time` TIME NOT NULL,
  INDEX `fk_course_slots_course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_course_slots_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `comp4004`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`deliverable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`deliverable` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`deliverable` (
  `deliverable_id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `deliverable_type` VARCHAR(45) NOT NULL,
  `deliverable_deadline` DATETIME NOT NULL,
  PRIMARY KEY (`deliverable_id`),
  INDEX `fk_deliverable_course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_deliverable_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `comp4004`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`login` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NOT NULL,
  `failed_time` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`preclusions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`preclusions` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`preclusions` (
  `course_id` INT NOT NULL,
  `preclusions_course_id` INT NOT NULL,
  INDEX `fk_preclusions_cours2_idx` (`preclusions_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_preclusions_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `comp4004`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`prerequisites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`prerequisites` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`prerequisites` (
  `course_id` INT NOT NULL,
  `prerequisites_course_id` INT NOT NULL,
  INDEX `fk_prerequisites_cours2_idx` (`prerequisites_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_prerequisites_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `comp4004`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`prof`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`prof` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`prof` (
  `prof_id` INT NOT NULL AUTO_INCREMENT,
  `prof_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`prof_id`),
  CONSTRAINT `fk_prof_login`
    FOREIGN KEY (`prof_id`)
    REFERENCES `comp4004`.`login` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`registration` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`registration` (
  `registration_id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `registration_date` DATETIME NOT NULL,
  `drop_date` DATETIME NULL,
  `late_registration` TINYINT NOT NULL,
  `late_registration_approval` TINYINT NULL,
  `late_drop` TINYINT NOT NULL,
  `late_drop_approval` TINYINT NULL,
  `final_grade` VARCHAR(45) NOT NULL DEFAULT 'N/A',
  INDEX `fk_registration_course_idx` (`course_id` ASC) VISIBLE,
  INDEX `fk_registration_student_idx` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`registration_id`),
  CONSTRAINT `unique_course_student` UNIQUE (`course_id`, `student_id`),
  CONSTRAINT `fk_registration_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `comp4004`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registration_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `comp4004`.`student` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`student` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(45) NOT NULL,
  `student_email` VARCHAR(45) NOT NULL,
  `admitted` TINYINT NOT NULL DEFAULT 0,
  `birth_date` DATE NOT NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `fk_student_login`
    FOREIGN KEY (`student_id`)
    REFERENCES `comp4004`.`login` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comp4004`.`submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comp4004`.`submission` ;

CREATE TABLE IF NOT EXISTS `comp4004`.`submission` (
  `submission_id` INT NOT NULL AUTO_INCREMENT,
  `registration_id` INT NOT NULL,
  `deliverable_id` INT NOT NULL,
  `submission_date` DATETIME NOT NULL,
  `submission_file` BLOB NULL,
  `file_type` VARCHAR(45) NOT NULL,
  `submission_grade` INT NULL,
  PRIMARY KEY (`submission_id`),
  INDEX `fk_submission_registration_idx` (`registration_id` ASC) VISIBLE,
  INDEX `fk_submission_deliverable_idx` (`deliverable_id` ASC) VISIBLE,
  CONSTRAINT `fk_submission_registration`
    FOREIGN KEY (`registration_id`)
    REFERENCES `comp4004`.`registration` (`registration_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submission_deliverable`
    FOREIGN KEY (`deliverable_id`)
    REFERENCES `comp4004`.`deliverable` (`deliverable_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
